// scripts/generate-sitemap.cjs
// Node.js script to generate sitemap.xml for all articles and language versions (CommonJS for Node.js)

const fs = require('fs');
const path = require('path');

// Read blogs from blogs.json (generated by fetch-blogs-supabase.mjs)
let blogs = [];
try {
  blogs = JSON.parse(fs.readFileSync(path.join(__dirname, 'blogs.json'), 'utf-8'));
} catch (e) {
  console.warn('Could not read blogs.json, using default. Run fetch-blogs-supabase.mjs first.');
  blogs = [
    { slug: 'blog-1', publish_date: '2025-12-30' }
  ];
}

const siteUrl = 'https://www.adventurousinvestorhub.com';
const staticPages = [
  '',
  'watch-read',
  'explore-ai',
];

let urls = [];

// Add static pages
staticPages.forEach(page => {
  urls.push({
    loc: `${siteUrl}/${page}`,
    lastmod: new Date().toISOString().split('T')[0],
    changefreq: 'weekly',
    priority: 1.0,
  });
});

// Add blog articles for hashrouter (single URL per article, no language param)
blogs.forEach(blog => {
  urls.push({
    loc: `${siteUrl}/#/blog/${blog.slug}`,
    lastmod: blog.publish_date,
    changefreq: 'monthly',
    priority: 0.8,
  });
});

const sitemapXml = `<?xml version="1.0" encoding="UTF-8"?>
<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">
${urls.map(url => `  <url>
    <loc>${url.loc}</loc>
    <lastmod>${url.lastmod}</lastmod>
    <changefreq>${url.changefreq}</changefreq>
    <priority>${url.priority}</priority>
  </url>`).join('\n')}
</urlset>`;

fs.writeFileSync(path.join(__dirname, '../public/sitemap.xml'), sitemapXml);
console.log('Sitemap generated at public/sitemap.xml');
